java -Xmx2g -jar HGS_Finder.jar all_genomes.ancestors_pass1 all_genomes.gd.fa Homo_Mus_Ciona_Branchiostoma_Drosophila_Nematostella_Hydra_Trichoplax_Amphimedon_Monosiga_Saccharomyces_Neurospora_Schizosaccharomyces_Dictyostelium_Arabidopsis_Volvox_Chlamydomonas_Thalassiosira_Phaeodactylum_Archae_Bacteria Amphimedon Archae_Bacteria


